import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ContextProvider from "@/context/ContextProvider";

export const metadata: Metadata = {
  title: "Tourigo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`font-inter bg-background showScrollbar`}
        suppressHydrationWarning={true}
      >
        <ContextProvider>
          
          {children}
          <Toaster richColors />
        </ContextProvider>
      </body>
    </html>
  );
}
